using AutoMapper;
using CarsManagement.Server.Domain.Entities;
using CarsManagement.Shared.DTO;

namespace CarsManagement.Server.Application;

public class ServerMapperProfile : Profile
{
    public ServerMapperProfile()
    {
        // Mapping for ManagerModel and ManagerDTO
        CreateMap<ManagerModel, ManagerDTO>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.AccountName, opt => opt.MapFrom(src => src.AccountName))
            .ForMember(dest => dest.ManagedParkingLots, opt => opt.MapFrom(src => src.ManagedParkingLots))
            .ReverseMap()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Assuming Id is autogenerated
            .ForMember(dest => dest.AccountName, opt => opt.MapFrom(src => src.AccountName))
            .ForMember(dest => dest.ManagedParkingLots, opt => opt.MapFrom(src => src.ManagedParkingLots));

        // Mapping for LotModel and ParkingLotDTO
        CreateMap<LotModel, ParkingLotDTO>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.ManagerId, opt => opt.MapFrom(src => src.ManagerId))
            .ForMember(dest => dest.LotName, opt => opt.MapFrom(src => src.LotName))
            .ForMember(dest => dest.LotLocation, opt => opt.MapFrom(src => src.LotLocation))
            .ForMember(dest => dest.ParkingSpots, opt => opt.MapFrom(src => src.ParkingSpots))
            .ReverseMap()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.ManagerId, opt => opt.MapFrom(src => src.ManagerId))
            .ForMember(dest => dest.LotName, opt => opt.MapFrom(src => src.LotName))
            .ForMember(dest => dest.LotLocation, opt => opt.MapFrom(src => src.LotLocation))
            .ForMember(dest => dest.ParkingSpots, opt => opt.MapFrom(src => src.ParkingSpots));

        // Mapping for SpotModel and ParkingSpotDTO
        CreateMap<SpotModel, ParkingSpotDTO>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.IsOccupied, opt => opt.MapFrom(src => src.IsOccupied))
            .ForMember(dest => dest.ParkedCar, opt => opt.MapFrom(src => src.ParkedCar))
            .ForMember(dest => dest.Ticket, opt => opt.MapFrom(src => src.Ticket))
            .ReverseMap()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.IsOccupied, opt => opt.MapFrom(src => src.IsOccupied))
            .ForMember(dest => dest.ParkedCar, opt => opt.MapFrom(src => src.ParkedCar))
            .ForMember(dest => dest.Ticket, opt => opt.MapFrom(src => src.Ticket));

        // Mapping for CarModel and CarDTO
        CreateMap<CarModel, CarDTO>()
            .ForMember(dest => dest.Brand, opt => opt.MapFrom(src => src.Brand))
            .ForMember(dest => dest.Model, opt => opt.MapFrom(src => src.Model))
            .ForMember(dest => dest.LicensePlate, opt => opt.MapFrom(src => src.LicensePlate))
            .ReverseMap();

        // Mapping for TicketModel and TicketDTO
        CreateMap<TicketModel, TicketDTO>()
            .ForMember(dest => dest.AmountPaid, opt => opt.MapFrom(src => src.AmountPaid))
            .ForMember(dest => dest.EntryTime, opt => opt.MapFrom(src => src.EntryTime))
            .ForMember(dest => dest.ExitTime, opt => opt.MapFrom(src => src.ExitTime))
            .ReverseMap();
    }
}